name: Build iOS Dylib

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Compile Dylib
        run: |
          xcrun -sdk iphoneos clang -dynamiclib -arch arm64 \
          -framework Foundation -framework WebKit -framework UIKit \
          -o ForceUserSelect.dylib \
          ForceUserSelect.m \
          -Wno-objc-method-access

          # 简单的签名，防止注入工具报错
          codesign -f -s - ForceUserSelect.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ForceUserSelect-Dylib
          path: ForceUserSelect.dylib
