name: Build iOS Dylib

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Compile Dylib
        run: |
          # 1. 确保文件名匹配！这里假设你上传的文件叫 ForceSwitch.m
          # 2. 必须添加 -framework UIKit，因为悬浮窗需要它
          
          xcrun -sdk iphoneos clang -dynamiclib -arch arm64 \
          -framework Foundation -framework WebKit -framework UIKit \
          -fobjc-arc \
          -o ForceSwitch.dylib \
          ForceSwitch.m \
          -Wno-objc-method-access

          # 3. 简单的伪签名
          codesign -f -s - ForceSwitch.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ForceSwitch-Dylib
          path: ForceSwitch.dylib
